version: '3'

volumes:
    tlscert:

services:

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
            - ./2017/static:/usr/share/static/2017:ro
            - ./2018/static:/usr/share/static/2018:ro
            - ./2019/static:/usr/share/static/2019:ro
            - tlscert:/etc/letsencrypt
        depends_on:
            - 2019_thehack_marko
            - 2018_thehack_marko
            - 2018_hackinit_marko
            - 2018_hackshanghai_marko
            - 2017_marko
            - letsencrypt

    2019_ambassador:
        restart: always
        build: ./2019/ambassador
        expose:
            - "3000"
        command: gulp server
        environment:
            - NODE_ENV='dev'
            - DATABASE='mongodb://${AMBASSADOR_MONGODB_USER}:${AMBASSADOR_MONGODB_PASS}@2019_ambassador_mongo:27017/ambassador'
            - JWT_SECRET=${JWT_SECRET}
            - ROOT_URL=${AMBASSADOR_URL}
            - ADMIN_EMAIL=${AMBASSADOR_ADMIN_EMAIL}
            - ADMIN_PASS=${AMBASSADOR_ADMIN_PASS}
            - EMAIL_CONTACT='THE Hack Marketing Team <marketing@hackinit.org>'
            - EMAIL_HOST=${AMBASSADOR_EMAIL_HOST}
            - EMAIL_USER=${AMBASSADOR_EMAIL}
            - EMAIL_PASS=${AMBASSADOR_EMAIL_PASS}
            - EMAIL_PORT=${AMBASSADOR_EMAIL_HOST_PORT}
            - EMAIL_HEADER_IMAGE='https://static.thehack.org.cn/2019/hackinit/email-header_900px.png'
            - EMAIL_ADDRESS=${AMBASSADOR_EMAIL}
            - HACKATHON_NAME='THE Hack'

    2019_ambassador_mongo:
        restart: always
        image: mongo:3.6.11-stretch
        expose:
            - "27017"
        volumes:
            - ./database/ambassador-mongo:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME:${AMBASSADOR_MONGODB_USER}
            - MONGO_INITDB_ROOT_PASSWORD:${AMBASSADOR_MONGODB_PASS}

    letsencrypt:
        restart: always
        image: adferrand/letsencrypt-dns:2.10.1
        environment:
            - LETSENCRYPT_USER_MAIL=ye.shu@hackinit.org
            - LEXICON_PROVIDER=cloudflare
            - LEXICON_CLOUDFLARE_USERNAME=${CF_EMAIL}
            - LEXICON_CLOUDFLARE_TOKEN=${CF_GLOBAL_API}
        volumes:
            - ./letsencrypt/domains.conf:/etc/letsencrypt/domains.conf
            - tlscert:/etc/letsencrypt

    2019_thehack_marko:
        restart: always
        build: ./2019/thehack/marko
        expose:
            - "8080"
        command: node app.js

    2018_hackinit_marko:
        restart: always
        build: ./2018/hackinit/marko
        expose:
            - "8080"
        command: node app.js

    2018_hackshanghai_marko:
        restart: always
        build: ./2018/hackshanghai/marko
        expose:
            - "8080"
        command: node app.js

    2018_thehack_marko:
        restart: always
        build: ./2018/thehack/marko
        expose:
            - "8080"
        command: node app.js

    2017_marko:
        restart: always
        build: ./2017/marko
        expose:
            - "8080"
        command: node app.js
