version: '2'

services:
    mongo:
        restart: always
        image: mongo:3.0.15-wheezy
        expose:
            - "27017"
        volumes:
            - ../db:/data/db

    quill:
        restart: always
        build: ./quill
        command: gulp server
        expose:
            - "3000"
        links:
            - mongo:mongo

    2017_marko:
        restart: always
        build: ./2017_marko
        expose:
            - "8080"
        command: node app.js

    2017_static:
        restart: always
        build: ./static

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - quill:quill
            - 2017_marko:2017_marko
        volumes_from:
            - 2017_static
