version: '2'

services:
    quill:
        restart: always
        build: ./quill
        command: gulp server
        expose:
            - "3000"
        network_mode: host

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - quill:quill
