version: '2'

services:
    hackinit_mongo:
        restart: always
        image: mongo:3.0.15-wheezy
        expose:
            - "27017"
        volumes:
            - ../db/hackinit:/data/db

    hackinit_quill:
        restart: always
        build: ./hackinit/quill
        command: gulp server
        expose:
            - "3000"
        links:
            - hackinit_mongo

    hackinit_marko:
        restart: always
        build: ./hackinit/marko
        expose:
            - "8080"
        command: node app.js

    hackinit_static:
        restart: always
        build: ./hackinit/static
        volumes:
            - ./hackinit/static:/usr/share/static/hackinit:ro

    hackshanghai_mongo:
        restart: always
        image: mongo:3.0.15-wheezy
        expose:
            - "27017"
        volumes:
            - ../db/hackshanghai:/data/db

    hackshanghai_quill:
        restart: always
        build: ./hackshanghai/quill
        command: gulp server
        expose:
            - "3000"
        links:
            - hackshanghai_mongo

    hackshanghai_marko:
        restart: always
        build: ./hackshanghai/marko
        expose:
            - "8080"
        command: node app.js

    hackshanghai_static:
        restart: always
        build: ./hackshanghai/static
        volumes:
            - ./hackshanghai/static:/usr/share/static/hackshanghai:ro

    thehack_marko:
        restart: always
        build: ./thehack/marko
        expose:
            - "8080"
        command: node app.js

    thehack_static:
        restart: always
        build: ./thehack/static
        volumes:
            - ./thehack/static:/usr/share/static/thehack:ro

    2017_marko:
        restart: always
        build: ./2017/marko
        expose:
            - "8080"
        command: node app.js

    2017_static:
        restart: always
        build: ./2017/static
        volumes:
            - ./2017/static:/usr/share/static/2017:ro

    django:
        restart: always
        build: django
        command: python manage.py runserver 0.0.0.0:8000
        expose:
            - "8000"
        env_file: secrets.env

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - hackinit_quill:hackinit_quill
            - hackinit_marko:hackinit_marko
            - hackinit_django:hackinit_django
            - hackshanghai_quill:hackshanghai_quill
            - hackshanghai_marko:hackshanghai_marko
            - hackshanghai_django:hackshanghai_django
            - thehack_marko:thehack_marko
            - 2017_marko:2017_marko
        volumes_from:
            - hackinit_static
            - hackshanghai_static
            - thehack_static
            - 2017_static
