version: '3'

services:

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
            - ./2017/static:/usr/share/static/2017:ro
            - ./2018/static:/usr/share/static/2018:ro
            - ./2019/static:/usr/share/static/2019:ro

    2019_thehack_marko:
        restart: always
        build: ./2019/thehack/marko
        expose:
            - "8080"
        command: node app.js

    2018_hackinit_marko:
        restart: always
        build: ./2018/hackinit/marko
        expose:
            - "8080"

    2018_hackshanghai_marko:
        restart: always
        build: ./2018/hackshanghai/marko
        expose:
            - "8080"

    2018_thehack_marko:
        restart: always
        build: ./2018/thehack/marko
        expose:
            - "8080"

    2017_marko:
        restart: always
        build: ./2017/marko
        expose:
            - "8080"
